spring.application.name=bingadmin-be
server.port=${MAIN_PORT}

# jwt
app.sec.jwt.at.secret=${JWT_AT_SCK}
app.sec.jwt.at.exp=${JWT_AT_EXP}
app.sec.jwt.rt.secret=${JWT_RT_SCK}
app.sec.jwt.rt.exp=${JWT_RT_EXP}

# oauth2
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID_GOOGLE}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET_GOOGLE}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code